# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

ENV['DO_SSHPORT'] ||= '22'
ENV['DO_KEYNAME'] ||= 'VAGRANT'
ENV['DO_INSTANCES'] ||= '1'



Vagrant.configure('2') do |config|
  config.ssh.port 		= ENV['DO_SSHPORT']
  config.ssh.username 	= 'root'

  ## For masterless, mount your salt file root
  config.vm.synced_folder "salt/roots/", "/srv/salt/"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
      salt.minion_config = "salt/minion"
      salt.verbose = true
      salt.run_highstate = true
  end

  (1..ENV['DO_INSTANCES'].to_i).each do |i|
    config.vm.define "U0-%02d"%i do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.vm.box			= 'digital_ocean'
        override.vm.box_url		= "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        override.ssh.private_key_path	= '~/.ssh/id_rsa'

        provider.ssh_key_name	= ENV['DO_KEYNAME']
        provider.token			= ENV['DO_TOKEN']
        provider.image			= 'docker'
        provider.region 		= 'ams3'
        provider.size			= '512MB'
        provider.setup			= false
        provider.private_networking	= true
        provider.user_data		= File.read('user-data.yml')
      end
    end
  end
end
