---
- hosts: all
  tasks:
    - name: install mc
      apt: name=mc update_cache=yes state=latest

    - name: tune mc to exit in current folder
      lineinfile: dest=/root/.profile line=". /usr/share/mc/bin/mc.sh" state=present insertafter=EOF

  roles:
    - williamyeh.oracle-java

  vars:
    java_version: 7